"""new fields in user model

Revision ID: 24332910d159
Revises: cb09794de6a5
Create Date: 2021-12-16 14:08:06.618254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24332910d159'
down_revision = 'cb09794de6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
