"""empty message

Revision ID: 4d852f4aee1a
Revises: 6c9fb7661bbc
Create Date: 2021-12-20 22:39:28.768808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d852f4aee1a'
down_revision = '6c9fb7661bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.add_column('user', sa.Column('current_room', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_room')
    op.create_table('room',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    # ### end Alembic commands ###
