"""added current_room parameter to users table

Revision ID: 6c9fb7661bbc
Revises: eae51768f4fc
Create Date: 2021-12-19 21:50:58.093281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9fb7661bbc'
down_revision = 'eae51768f4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.add_column('user', sa.Column('current_room', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_room')
    op.create_table('room',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    # ### end Alembic commands ###
